-- AlterTable
ALTER TABLE "group_settings" ADD COLUMN     "phone_calls_usable_by_adults" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_usable_by_caregivers" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_usable_by_children" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_usable_by_parents" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_visible_to_adults" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_visible_to_caregivers" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_visible_to_children" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_visible_to_parents" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_visible_to_supervisors" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "record_phone_calls" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "record_video_calls" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_usable_by_adults" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_usable_by_caregivers" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_usable_by_children" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_usable_by_parents" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_visible_to_adults" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_visible_to_caregivers" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_visible_to_children" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_visible_to_parents" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_visible_to_supervisors" BOOLEAN NOT NULL DEFAULT false;
