-- AlterTable: Add admin role permission fields to group_settings
ALTER TABLE "group_settings" ADD COLUMN     "calendar_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "calendar_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "documents_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "documents_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "finance_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "finance_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "gift_registry_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "gift_registry_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "item_registry_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "item_registry_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "message_groups_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "message_groups_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_usable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone_calls_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "secret_santa_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "secret_santa_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_usable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "video_calls_visible_to_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "wiki_creatable_by_admins" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "wiki_visible_to_admins" BOOLEAN NOT NULL DEFAULT true;
